# java 中的根异常

> 原文:[https://www.tutorialandexample.com/root-exception-in-java](https://www.tutorialandexample.com/root-exception-in-java)

## Java:

java 的主要特点是平台无关性，这不是 C 语言或面向对象编程语言的特点。不仅仅是平台无关性，java 还有许多其他的特性，如安全、高度解释、健壮、可移植等。此外，类和对象始终用于编写 Java 代码。

## 例外情况:

程序执行过程中出现的问题被称为异常(或异常事件)。当出现异常时，程序的正常流程被中断，程序/应用程序意外终止，这是不建议的。因此，需要处理这些异常。

许多因素都会导致异常。下面是发生异常的各种情况。用户输入了不正确的信息。找不到需要打开的文件。

JVM 内存不足，或者网络连接在通信过程中丢失。这些异常中的其他一些是由用户错误引起的，一些是由编程错误引起的，一些是由物理资源不足引起的。

## 根异常:

使用嵌套异常在 Java 中相当普遍，因为它们使得识别问题的原因更容易。在处理这类异常时，有时我们可能希望知道导致异常的潜在问题，以便我们的应用程序可以在每种情况下做出适当的反应。

当使用将根异常封装到自己的框架中时，这是非常有用的。

异常类的层次结构用于安排 Java 程序中的潜在异常。异常层次结构的基础是 Throwable 类，它是 Object 的直接子类。异常和错误是 Throwable 的两个直接子类。

throwable 的内置 get Cause()方法返回异常的原因，如果无法确定异常的原因，则返回 null。由其中一个构造函数提供的原因或在创建后用 init Cause ( Throwable)方法设置的原因可以使用此方法获得。

为了确定 Throwable 或异常的来源，Throwable 类的打印堆栈跟踪方法调用 get Cause()函数。有人可能会说，这个方法只是返回异常发生的原因。现在让我们看看定义 get Cause()方法的语法，如下所示。

### 定义方法 get Cause()的语法:

为了定义一个方法或变量或任何编程语言中的任何关键字，将会有特定的语法。所以定义方法 get Cause()的语法如下所示:

```
public Throwable get Cause ( )
```

现在让我们看一个例子，使用如下所示的代码来查找 java 程序的根异常:

**举例:**

```
import java . io . *;
class Demo
{
public static void main ( String args [ ] ) throws Exception
{
try
{
division ( 15,0 );
} // try block
catch ( ArithmeticException ae )
{
System.out.println ( “ The cause of exception is : “ + ae.getCause ( ) );
} // catch block
} // main method
public static void division ( int m , int n ) throws Exception
{
try
{
int i = m / n ;
} // try block
catch ( ArithmeticException ae )
{
arithmeticException ans = new ArithmeticException ( ) ;
ans . init Cause ( ae );
throw ( ans );
} // catch block
} // division 
} // demo class
```

**输出:**

```
Cause of Exception : java . lang . ArithmeticException : / by zero
```

现在让我们看另一个例子，使用如下所示的代码查找 java 程序的根异常:

**举例:**

```
import java . io . *;
class Demo
{
public static void main ( String args [ ] ) throws Exception
{
try
{
division ( 15,0 );
} // try block
catch ( ArithmeticException ae )
{
System.out.println ( “ The cause of exception is : “ + ae.getCause ( ) );
} // catch block
} // main method
public static void division ( int m , int n ) throws Exception
{
int i = m / n ;
} // division 
} // demo class
```

**输出:**

```
Cause of Exception : null
```